# Generated by Django 6.1.2 on 2026-10-08 11:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=16, verbose_name='ФН')),
                ('fd', models.CharField(max_length=20, verbose_name='ФД')),
                ('fp', models.CharField(max_length=20, verbose_name='ФП')),
                ('purchased_at', models.DateTimeField(verbose_name='Дата и время покупки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=16, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['-purchased_at', '-id'],
                'indexes': [models.Index(fields=['user', '-purchased_at'], name='lucky_recei_user_id_1d4f34_idx')],
                'constraints': [models.UniqueConstraint(fields=('fn', 'fd', 'fp'), name='uniq_receipt_fn_fd_fp')],
            },
        ),
    ]
