# Generated by Django 6.1.2 on 2026-10-08 13:48

import django.db.models.deletion
import lucky_receipt.models
import lucky_receipt.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_receipt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=lucky_receipt.models.receipt_photo_path, validators=[lucky_receipt.validators.validate_receipt_photo], verbose_name='Фото чека')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Фото чека',
                'verbose_name_plural': 'Фото чеков',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterConstraint(
            model_name='receipt',
            name='uniq_receipt_fn_fd_fp',
            constraint=models.UniqueConstraint(fields=('fn', 'fd', 'fp'), name='uniq_receipt_fn_fd_fp', violation_error_message='Чек с такими ФН, ФД и ФП уже зарегистрирован'),
        ),
        migrations.AddField(
            model_name='receiptphoto',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='lucky_receipt.receipt', verbose_name='Чек'),
        ),
    ]
