# Generated by Django 6.1.2 on 2026-10-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_receipt', '0002_receiptphoto_alter_receipt_uniq_receipt_fn_fd_fp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='receipt',
            name='moderator_comment',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
    ]
