# Generated by Django 6.1.2 on 2026-10-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_receipt', '0003_remove_receipt_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('won', 'Вы выиграли')], default='pending', max_length=16, verbose_name='Статус'),
        ),
    ]
